"""add search_items_table

Revision ID: 32b8169bad1a
Revises: 370ef3d0e699
Create Date: 2025-03-25 23:07:01.596137

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32b8169bad1a"
down_revision = "370ef3d0e699"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_items",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_items")
    # ### end Alembic commands ###
