"""big integer for chat_id

Revision ID: 370ef3d0e699
Revises: ddb1bdf37e97
Create Date: 2024-04-06 23:28:33.774833

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "370ef3d0e699"
down_revision = "ddb1bdf37e97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "chat_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "chat_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
