"""added tracking records table

Revision ID: 44402487a7d0
Revises: fdfc105760c1
Create Date: 2024-04-05 22:32:56.598415

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44402487a7d0"
down_revision = "fdfc105760c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("value", sa.Float(precision=2), nullable=True),
        sa.Column(
            "measure_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracking_records_client_id"),
        "tracking_records",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_records_currency"),
        "tracking_records",
        ["currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_records_id"),
        "tracking_records",
        ["id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tracking_records_id"), table_name="tracking_records"
    )
    op.drop_index(
        op.f("ix_tracking_records_currency"), table_name="tracking_records"
    )
    op.drop_index(
        op.f("ix_tracking_records_client_id"), table_name="tracking_records"
    )
    op.drop_table("tracking_records")
    # ### end Alembic commands ###
