"""init

Revision ID: d02ca4574ae0
Revises: 
Create Date: 2023-04-15 16:11:49.301407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d02ca4574ae0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=True)
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_index(op.f("ix_agents_side"), "agents", ["side"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("item_limit", sa.Integer(), nullable=True),
        sa.Column("lang", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", "chat_id"),
    )
    op.create_index(op.f("ix_clients_chat_id"), "clients", ["chat_id"], unique=True)
    op.create_index(op.f("ix_clients_currency"), "clients", ["currency"], unique=False)
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=True)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "containers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("container_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_containers_id"), "containers", ["id"], unique=True)
    op.create_index(op.f("ix_containers_name"), "containers", ["name"], unique=False)
    op.create_table(
        "price_limits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("value", sa.Float(precision=2), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_limits_currency"), "price_limits", ["currency"], unique=True
    )
    op.create_index(op.f("ix_price_limits_id"), "price_limits", ["id"], unique=True)
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=True),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", "name", "currency"),
        sa.UniqueConstraint("name", "currency", name="_name_currency_uc"),
    )
    op.create_index(op.f("ix_prices_currency"), "prices", ["currency"], unique=False)
    op.create_index(op.f("ix_prices_id"), "prices", ["id"], unique=True)
    op.create_index(op.f("ix_prices_name"), "prices", ["name"], unique=False)
    op.create_table(
        "skins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skin_type", sa.String(), nullable=False),
        sa.Column("collection", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("skin", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("fn", sa.Boolean(), nullable=True),
        sa.Column("mw", sa.Boolean(), nullable=True),
        sa.Column("ft", sa.Boolean(), nullable=True),
        sa.Column("ww", sa.Boolean(), nullable=True),
        sa.Column("bs", sa.Boolean(), nullable=True),
        sa.Column("st", sa.Boolean(), nullable=True),
        sa.Column("sv", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skins_collection"), "skins", ["collection"], unique=False)
    op.create_index(op.f("ix_skins_full_name"), "skins", ["full_name"], unique=False)
    op.create_index(op.f("ix_skins_id"), "skins", ["id"], unique=True)
    op.create_index(op.f("ix_skins_name"), "skins", ["name"], unique=False)
    op.create_index(op.f("ix_skins_skin"), "skins", ["skin"], unique=False)
    op.create_index(op.f("ix_skins_skin_type"), "skins", ["skin_type"], unique=False)
    op.create_table(
        "stickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sticker_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("collection", sa.String(), nullable=True),
        sa.Column("tournament", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stickers_full_name"), "stickers", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_stickers_id"), "stickers", ["id"], unique=True)
    op.create_index(op.f("ix_stickers_name"), "stickers", ["name"], unique=False)
    op.create_index(
        op.f("ix_stickers_sticker_type"), "stickers", ["sticker_type"], unique=False
    )
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tools_id"), "tools", ["id"], unique=True)
    op.create_index(op.f("ix_tools_name"), "tools", ["name"], unique=True)
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("app_name", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("take_profit", sa.Float(precision=2), nullable=True),
        sa.Column("stop_loss", sa.Float(precision=2), nullable=True),
        sa.Column("profit_notify", sa.Boolean(), nullable=True),
        sa.Column("loss_notify", sa.Boolean(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id", "name"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_items_client_id"), "items", ["client_id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_table(
        "deals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("deal_type", sa.String(), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("deal_currency", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_deals_client_id"), "deals", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_deals_deal_currency"), "deals", ["deal_currency"], unique=False
    )
    op.create_index(op.f("ix_deals_deal_type"), "deals", ["deal_type"], unique=False)
    op.create_index(op.f("ix_deals_item_id"), "deals", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deals_item_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_deal_type"), table_name="deals")
    op.drop_index(op.f("ix_deals_deal_currency"), table_name="deals")
    op.drop_index(op.f("ix_deals_client_id"), table_name="deals")
    op.drop_table("deals")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_client_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_tools_name"), table_name="tools")
    op.drop_index(op.f("ix_tools_id"), table_name="tools")
    op.drop_table("tools")
    op.drop_index(op.f("ix_stickers_sticker_type"), table_name="stickers")
    op.drop_index(op.f("ix_stickers_name"), table_name="stickers")
    op.drop_index(op.f("ix_stickers_id"), table_name="stickers")
    op.drop_index(op.f("ix_stickers_full_name"), table_name="stickers")
    op.drop_table("stickers")
    op.drop_index(op.f("ix_skins_skin_type"), table_name="skins")
    op.drop_index(op.f("ix_skins_skin"), table_name="skins")
    op.drop_index(op.f("ix_skins_name"), table_name="skins")
    op.drop_index(op.f("ix_skins_id"), table_name="skins")
    op.drop_index(op.f("ix_skins_full_name"), table_name="skins")
    op.drop_index(op.f("ix_skins_collection"), table_name="skins")
    op.drop_table("skins")
    op.drop_index(op.f("ix_prices_name"), table_name="prices")
    op.drop_index(op.f("ix_prices_id"), table_name="prices")
    op.drop_index(op.f("ix_prices_currency"), table_name="prices")
    op.drop_table("prices")
    op.drop_index(op.f("ix_price_limits_id"), table_name="price_limits")
    op.drop_index(op.f("ix_price_limits_currency"), table_name="price_limits")
    op.drop_table("price_limits")
    op.drop_index(op.f("ix_containers_name"), table_name="containers")
    op.drop_index(op.f("ix_containers_id"), table_name="containers")
    op.drop_table("containers")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_currency"), table_name="clients")
    op.drop_index(op.f("ix_clients_chat_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_agents_side"), table_name="agents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
