"""add income column

Revision ID: ddb1bdf37e97
Revises: 44402487a7d0
Create Date: 2024-04-06 18:24:45.034465

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddb1bdf37e97"
down_revision = "44402487a7d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracking_records", sa.Column("income", sa.Float(precision=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracking_records", "income")
    # ### end Alembic commands ###
