"""Second migration

Revision ID: fdfc105760c1
Revises: d02ca4574ae0
Create Date: 2023-04-16 21:57:22.775745

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "fdfc105760c1"
down_revision = "d02ca4574ae0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "deals", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deals", type_="unique")
    # ### end Alembic commands ###
