"""Initial

Revision ID: 30746ac5ec04
Revises: 
Create Date: 2021-06-16 23:16:56.475195

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '30746ac5ec04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("deals_id_uc", 'deals', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("deals_id_uc", 'deals', type_='unique')
    # ### end Alembic commands ###
