"""Remove bool indexes

Revision ID: 6535440fe9dc
Revises: 96af73d624cf
Create Date: 2021-06-17 22:17:07.599788

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6535440fe9dc'
down_revision = '96af73d624cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deals_closed', table_name='deals')
    op.drop_index('ix_items_loss_notify', table_name='items')
    op.drop_index('ix_items_profit_notify', table_name='items')
    op.drop_index('ix_skins_bs', table_name='skins')
    op.drop_index('ix_skins_fn', table_name='skins')
    op.drop_index('ix_skins_ft', table_name='skins')
    op.drop_index('ix_skins_mw', table_name='skins')
    op.drop_index('ix_skins_st', table_name='skins')
    op.drop_index('ix_skins_sv', table_name='skins')
    op.drop_index('ix_skins_ww', table_name='skins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_skins_ww', 'skins', ['ww'], unique=False)
    op.create_index('ix_skins_sv', 'skins', ['sv'], unique=False)
    op.create_index('ix_skins_st', 'skins', ['st'], unique=False)
    op.create_index('ix_skins_mw', 'skins', ['mw'], unique=False)
    op.create_index('ix_skins_ft', 'skins', ['ft'], unique=False)
    op.create_index('ix_skins_fn', 'skins', ['fn'], unique=False)
    op.create_index('ix_skins_bs', 'skins', ['bs'], unique=False)
    op.create_index('ix_items_profit_notify', 'items', ['profit_notify'], unique=False)
    op.create_index('ix_items_loss_notify', 'items', ['loss_notify'], unique=False)
    op.create_index('ix_deals_closed', 'deals', ['closed'], unique=False)
    # ### end Alembic commands ###
