"""Clean items and deals models

Revision ID: 96af73d624cf
Revises: 30746ac5ec04
Create Date: 2021-06-17 22:11:04.116321

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '96af73d624cf'
down_revision = '30746ac5ec04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_premium', table_name='clients')
    op.drop_index('ix_clients_profit', table_name='clients')
    op.drop_index('ix_clients_profit_limit', table_name='clients')
    op.drop_column('clients', 'premium')
    op.drop_column('clients', 'profit')
    op.drop_column('clients', 'profit_limit')
    op.drop_index('ix_items_favorite', table_name='items')
    op.drop_index('ix_items_profit', table_name='items')
    op.drop_index('ix_items_tracking', table_name='items')
    op.drop_column('items', 'favorite')
    op.drop_column('items', 'profit')
    op.drop_column('items', 'tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tracking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('profit', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_items_tracking', 'items', ['tracking'], unique=False)
    op.create_index('ix_items_profit', 'items', ['profit'], unique=False)
    op.create_index('ix_items_favorite', 'items', ['favorite'], unique=False)
    op.add_column('clients', sa.Column('profit_limit', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('profit', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_clients_profit_limit', 'clients', ['profit_limit'], unique=False)
    op.create_index('ix_clients_profit', 'clients', ['profit'], unique=False)
    op.create_index('ix_clients_premium', 'clients', ['premium'], unique=False)
    # ### end Alembic commands ###
