"""remove password field

Revision ID: b8d66b2b26f4
Revises: 6535440fe9dc
Create Date: 2021-06-20 14:53:41.059036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8d66b2b26f4'
down_revision = '6535440fe9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_password', table_name='clients')
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_clients_password', 'clients', ['password'], unique=False)
    # ### end Alembic commands ###
